import type { NextRequest } from "next/server";
import { isAuthorized } from "@/lib/server-auth";
import { searchNetwork } from "@/lib/mock-search";
import type { Connection } from "@/lib/types";

// Chat reply is generated by Gemini (gemini-3.1-flash-lite, 0 thinking budget).
// Matched people still come from the stubbed network search and are sent as
// grounding context + rendered as cards. This is intentionally basic — the
// backend will optimize retrieval + prompting later.
//
// Wire protocol = newline-delimited JSON:
//   {"type":"matches","matches":[...]}   (once, first)
//   {"type":"delta","text":"..."}        (many)
const GEMINI_MODEL = "gemini-3.1-flash-lite";

const SYSTEM_INSTRUCTION =
  "You are thinkedin, an assistant that helps a user search and understand their " +
  "professional (LinkedIn) network. Be concise and specific. Reference the provided " +
  "connections by name, explain briefly why each is relevant, and suggest an intro " +
  "angle when useful. If no connections are provided, say you couldn't find a match. " +
  "Keep it short. Write in short flowing sentences — do NOT use markdown bullet lists, " +
  "headers, or tables. You may use **bold** for people's names.";

interface HistoryItem {
  role: "user" | "assistant";
  content: string;
}

export async function POST(request: NextRequest) {
  if (!(await isAuthorized(request))) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  let message = "";
  let history: HistoryItem[] = [];
  try {
    const body = await request.json();
    message = typeof body?.message === "string" ? body.message : "";
    if (Array.isArray(body?.history)) history = body.history;
  } catch {
    // empty message handled below
  }

  const { matches, matchedConnections, reply } = searchNetwork(message);
  const encoder = new TextEncoder();

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      const send = (obj: unknown) =>
        controller.enqueue(encoder.encode(JSON.stringify(obj) + "\n"));

      // Surface matched people first so the UI can render cards immediately.
      send({ type: "matches", matches });

      try {
        await streamGemini({
          message,
          history,
          connections: matchedConnections,
          onText: (text) => send({ type: "delta", text }),
        });
      } catch {
        // Fall back to the deterministic mock reply so chat never dead-ends.
        for (const token of reply.match(/\S+\s*/g) ?? [reply]) {
          send({ type: "delta", text: token });
          await new Promise((r) => setTimeout(r, 18));
        }
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "application/x-ndjson; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
    },
  });
}

function buildContextBlock(connections: Connection[]): string {
  if (!connections.length) return "No relevant connections were found in the network.";
  return connections
    .map((c) => {
      const where = c.location ? `, ${c.location}` : "";
      return `- ${c.name} — ${c.position} at ${c.company}${where}. ${c.summary ?? ""}`.trim();
    })
    .join("\n");
}

async function streamGemini({
  message,
  history,
  connections,
  onText,
}: {
  message: string;
  history: HistoryItem[];
  connections: Connection[];
  onText: (text: string) => void;
}) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY not set");

  const contents = [
    ...history.map((h) => ({
      role: h.role === "assistant" ? "model" : "user",
      parts: [{ text: h.content }],
    })),
    {
      role: "user",
      parts: [
        {
          text: `${message}\n\nRelevant connections from the user's network:\n${buildContextBlock(connections)}`,
        },
      ],
    },
  ];

  const url =
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:streamGenerateContent` +
    `?alt=sse&key=${apiKey}`;

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: SYSTEM_INSTRUCTION }] },
      contents,
      generationConfig: { thinkingConfig: { thinkingBudget: 0 } },
    }),
  });

  if (!res.ok || !res.body) {
    throw new Error(`Gemini request failed: ${res.status}`);
  }

  // Parse the SSE stream: lines of `data: { ...candidates... }`.
  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let emitted = false;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });

    let nl: number;
    while ((nl = buffer.indexOf("\n")) !== -1) {
      const line = buffer.slice(0, nl).trim();
      buffer = buffer.slice(nl + 1);
      if (!line.startsWith("data:")) continue;

      const payload = line.slice(5).trim();
      if (!payload || payload === "[DONE]") continue;

      const json = JSON.parse(payload);
      const parts = json?.candidates?.[0]?.content?.parts ?? [];
      for (const part of parts) {
        if (typeof part?.text === "string" && !part.thought) {
          onText(part.text);
          emitted = true;
        }
      }
    }
  }

  if (!emitted) throw new Error("Gemini returned no text");
}
